import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

type TRootLayout = {
  children: React.ReactNode;
};

const RootLayout: React.FC<TRootLayout> = ({ children }) => {
  const teste = 'teste';
  const teste2 = 'teste';

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
